// Generated by ReScript, PLEASE EDIT WITH CARE

import * as App from "@monorepo/app/src/App.mjs";

App.main();

let rootValue = "Root package";

let unusedRootValue = 123;

export {
  rootValue,
  unusedRootValue,
}
/*  Not a pure module */
