// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Fs = require("fs");
var Tools_Docgen = require("../src/Tools_Docgen.bs.js");

var json = JSON.parse(Fs.readFileSync("./test.json"));

console.log(Tools_Docgen.decodeFromJson(json));

exports.json = json;
/* json Not a pure module */
