// Generated by ReScript, PLEASE EDIT WITH CARE


throw {
      RE_EXN_ID: "Assert_failure",
      _1: [
        "Chess.res",
        6,
        56
      ],
      Error: new Error()
    };

export {
  computeScore ,
  findNextMoves ,
  makeMove ,
  chess ,
  
}
/* computeScore Not a pure module */
