// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Json$JsonCombinators from "@glennsl/rescript-json-combinators/src/Json.bs.js";
import * as Json_Decode$JsonCombinators from "@glennsl/rescript-json-combinators/src/Json_Decode.bs.js";

function testBsJson2(x) {
  return Json$JsonCombinators.decode(x, Json_Decode$JsonCombinators.string);
}

export {
  testBsJson2 ,
}
/* No side effect */
