// Generated by ReScript, PLEASE EDIT WITH CARE

import * as PervasivesU from "rescript/lib/es6/pervasivesU.js";

function wrapExitTop(x) {
  return PervasivesU.exit(x);
}

function wrapExitM1(x) {
  return PervasivesU.exit(x);
}

function callLocally(x) {
  return PervasivesU.exit(x);
}

function callTop(x) {
  return PervasivesU.exit(x);
}

function wrapExitM2(x) {
  return PervasivesU.exit(x);
}

function callM1(x) {
  return PervasivesU.exit(x);
}

function callTop$1(x) {
  return PervasivesU.exit(x);
}

var M2 = {
  wrapExitM2: wrapExitM2,
  callM1: callM1,
  callTop: callTop$1
};

var M1 = {
  wrapExitM1: wrapExitM1,
  callLocally: callLocally,
  callTop: callTop,
  M2: M2
};

function callM1$1(x) {
  return PervasivesU.exit(x);
}

export {
  wrapExitTop ,
  M1 ,
  callM1$1 as callM1,
}
/* No side effect */
