// Generated by ReScript, PLEASE EDIT WITH CARE

import * as InnerModules from "./InnerModules.bs.js";

function testTop(x) {
  return InnerModules.wrapExitTop(x);
}

function testM1(x) {
  return InnerModules.M1.wrapExitM1(x);
}

function testM2(x) {
  return InnerModules.M1.M2.wrapExitM2(x);
}

export {
  testTop ,
  testM1 ,
  testM2 ,
}
/* No side effect */
