// Generated by ReScript, PLEASE EDIT WITH CARE


function add(a, b) {
  return a + b | 0;
}

var greeting = "Hello from ReScript 9!";

var result = 3;

export {
  greeting ,
  add ,
  result ,
  
}
/* No side effect */
