module QQ =
  struct
    let thisSpansSeveralLines =
      (fun x -> fun y ->
          x + y : int -> int -> int)
  end

module AA : sig
  val thisIsInInterface :
    int -> int
end = struct
  let thisIsInInterface x = x
end

let thisHasSemicolons = 3;;

type thisIsDead = | DeadA | DeadB


let () = 
  let _ = 3 in
  let _ = [1,2,3] in 
  ()

module Bs_version :
  sig val version : string val header : string val package_name : string end 
  =
  struct
    let version = "7.2.0-dev.4"
    let header = "// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE"
    let package_name = "bs-platform"
  end 

type l =
  | Lfunction of   { arity : int ; 
                     params : int list ;
                     body : string 
                       }

type module_info = {
  module_name: string;
  case: bool
}

let rec map_split_opt 
  (xs : 'a list)  (f : 'a -> 'b option * 'c option) 
  : 'b list * 'c list = 
  match xs with 
  | [] -> [], []
  | x::xs ->
    let c,d = f x in 
    let cs,ds = map_split_opt xs f in 
    (match c with Some c -> c::cs | None -> cs),
    (match d with Some d -> d::ds | None -> ds)

let inline_threshold = Some (10. /. 8.);

module Scope = struct
  let dead1 = 1

  module Inner1 = struct
    let deadInner1 = 0

    [@@@ocaml.warning "-32"]

    let liveInner2 = 0
  end

  let dead2 = 2

  [@@@ocaml.warning "-32"]

  module Inner2 = struct
    let liveInner3 = 0
  end

  let live3 = 3
end

let dead4 = 4

let live5 = 5
[@@ocaml.warning "-32"]

let dead5 = 5

let live6 = 6
[@@ocaml.warning "xxx-32xxx"]

let dead7 = 7
[@@ocaml.warning "-30"]

module WithSignature : sig
  val dead8: int

  val live9: int
  [@@ocaml.warning "-32"]

  val dead10: int

  [@@@ocaml.warning "-32"]

  val live11: int
end =
struct
  let dead8 = 8
  let live9 = 9
  let dead10 = 10
  let live11 = 11
end

let [@warning "-32"] foo x = print_int x

let [@warning "-unused-value-declaration"] bar x = print_int x
