// Generated by ReScript, PLEASE EDIT WITH CARE


function Make($$Error) {
  var notify = function (x) {
    return $$Error.notification(x);
  };
  return {
          notify: notify
        };
}

var x = 42;

export {
  Make ,
  x ,
}
/* No side effect */
