// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Belt_Array from "rescript/lib/es6/belt_Array.js";

function fromArray(a) {
  return a.slice(0);
}

function toArray(a) {
  return a.slice(0);
}

function length(a) {
  return a.length;
}

function size(a) {
  return a.length;
}

var get = Belt_Array.get;

var getExn = Belt_Array.getExn;

function getUnsafe(a, x) {
  return a[x];
}

function getUndefined(a, x) {
  return a[x];
}

var shuffle = Belt_Array.shuffle;

var reverse = Belt_Array.reverse;

function makeUninitialized(x) {
  return new Array(x);
}

function makeUninitializedUnsafe(x) {
  return new Array(x);
}

var make = Belt_Array.make;

var range = Belt_Array.range;

var rangeBy = Belt_Array.rangeBy;

var makeByU = Belt_Array.makeByU;

var makeBy = Belt_Array.makeByU;

var makeByAndShuffleU = Belt_Array.makeByAndShuffleU;

var makeByAndShuffle = Belt_Array.makeByAndShuffleU;

var zip = Belt_Array.zip;

var zipByU = Belt_Array.zipByU;

var zipBy = Belt_Array.zipByU;

var unzip = Belt_Array.unzip;

var concat = Belt_Array.concat;

var concatMany = Belt_Array.concatMany;

var slice = Belt_Array.slice;

var sliceToEnd = Belt_Array.sliceToEnd;

function copy(a) {
  return a.slice(0);
}

var forEachU = Belt_Array.forEachU;

var forEach = Belt_Array.forEachU;

var mapU = Belt_Array.mapU;

var map = Belt_Array.mapU;

var keepWithIndexU = Belt_Array.keepWithIndexU;

var keepWithIndex = Belt_Array.keepWithIndexU;

var keepMapU = Belt_Array.keepMapU;

var keepMap = Belt_Array.keepMapU;

var forEachWithIndexU = Belt_Array.forEachWithIndexU;

var forEachWithIndex = Belt_Array.forEachWithIndexU;

var mapWithIndexU = Belt_Array.mapWithIndexU;

var mapWithIndex = Belt_Array.mapWithIndexU;

var partitionU = Belt_Array.partitionU;

var partition = Belt_Array.partitionU;

var reduceU = Belt_Array.reduceU;

var reduce = Belt_Array.reduceU;

var reduceReverseU = Belt_Array.reduceReverseU;

var reduceReverse = Belt_Array.reduceReverseU;

var reduceReverse2U = Belt_Array.reduceReverse2U;

var reduceReverse2 = Belt_Array.reduceReverse2U;

var someU = Belt_Array.someU;

var some = Belt_Array.someU;

var everyU = Belt_Array.everyU;

var every = Belt_Array.everyU;

var every2U = Belt_Array.every2U;

var every2 = Belt_Array.every2U;

var some2U = Belt_Array.some2U;

var some2 = Belt_Array.some2U;

var cmpU = Belt_Array.cmpU;

var cmp = Belt_Array.cmpU;

var eqU = Belt_Array.eqU;

var eq = Belt_Array.eqU;

var $$Array$1 = {
  get: get
};

export {
  $$Array$1 as $$Array,
  fromArray ,
  toArray ,
  length ,
  size ,
  get ,
  getExn ,
  getUnsafe ,
  getUndefined ,
  shuffle ,
  reverse ,
  makeUninitialized ,
  makeUninitializedUnsafe ,
  make ,
  range ,
  rangeBy ,
  makeByU ,
  makeBy ,
  makeByAndShuffleU ,
  makeByAndShuffle ,
  zip ,
  zipByU ,
  zipBy ,
  unzip ,
  concat ,
  concatMany ,
  slice ,
  sliceToEnd ,
  copy ,
  forEachU ,
  forEach ,
  mapU ,
  map ,
  keepWithIndexU ,
  keepWithIndex ,
  keepMapU ,
  keepMap ,
  forEachWithIndexU ,
  forEachWithIndex ,
  mapWithIndexU ,
  mapWithIndex ,
  partitionU ,
  partition ,
  reduceU ,
  reduce ,
  reduceReverseU ,
  reduceReverse ,
  reduceReverse2U ,
  reduceReverse2 ,
  someU ,
  some ,
  everyU ,
  every ,
  every2U ,
  every2 ,
  some2U ,
  some2 ,
  cmpU ,
  cmp ,
  eqU ,
  eq ,
}
/* No side effect */
