// Generated by ReScript, PLEASE EDIT WITH CARE

import * as JsxRuntime from "react/jsx-runtime";

function JsxV4$C(props) {
  return null;
}

var C = {
  make: JsxV4$C
};

JsxRuntime.jsx(JsxV4$C, {});

export {
  C ,
}
/*  Not a pure module */
