// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Caml_format from "rescript/lib/es6/caml_format.js";
import * as Caml_js_exceptions from "rescript/lib/es6/caml_js_exceptions.js";
import * as Caml_external_polyfill from "rescript/lib/es6/caml_external_polyfill.js";

function to_string(n) {
  return Caml_format.caml_nativeint_format("%d", n);
}

function of_string_opt(s) {
  try {
    return Caml_format.caml_nativeint_of_string(s);
  }
  catch (raw_exn){
    var exn = Caml_js_exceptions.internalToOCamlException(raw_exn);
    if (exn.RE_EXN_ID === "Failure") {
      return ;
    }
    throw exn;
  }
}

function compare(x, y) {
  return Caml_external_polyfill.resolve("caml_nativeint_compare")(x, y);
}

function equal(x, y) {
  return Caml_external_polyfill.resolve("caml_nativeint_compare")(x, y) === 0;
}

export {
  to_string ,
  of_string_opt ,
  compare ,
  equal ,
  
}
/* No side effect */
