// Generated by ReScript, PLEASE EDIT WITH CARE


function group(breakOpt, doc) {
  var $$break = breakOpt !== undefined ? breakOpt : "IfNeed";
  return {
          break: $$break,
          doc: doc
        };
}

function fits(_w, _stack) {
  while(true) {
    var stack = _stack;
    var w = _w;
    if (w < 0) {
      return false;
    }
    if (typeof stack !== "object") {
      return true;
    }
    _stack = stack._1;
    _w = w - stack._0.doc.length | 0;
    continue ;
  };
}

function toString(width, stack) {
  if (typeof stack !== "object") {
    return "";
  }
  var stack$1 = stack._1;
  var match = stack._0;
  var doc = match.doc;
  switch (match.break) {
    case "IfNeed" :
        return (
                fits(width, stack$1) ? "fits " : "no "
              ) + toString(width - 1 | 0, stack$1);
    case "Never" :
        return "never " + (doc + toString(width - 1 | 0, stack$1));
    case "Always" :
        return "always " + (doc + toString(width - 1 | 0, stack$1));
    
  }
}

toString(80, "Empty");

var $$break = "Never";

toString(80, {
      TAG: "Cons",
      _0: {
        break: $$break,
        doc: "abc"
      },
      _1: "Empty"
    });

var $$break$1 = "Always";

toString(80, {
      TAG: "Cons",
      _0: {
        break: $$break$1,
        doc: "d"
      },
      _1: "Empty"
    });

export {
  group ,
  fits ,
  toString ,
}
/*  Not a pure module */
