// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Lib from "@monorepo/lib/src/Lib.mjs";

function main() {
  let greeting = Lib.greet("World");
  console.log(greeting);
  let sum = Lib.add(1, 2);
  console.log("Sum: " + sum.toString());
}

function unusedAppFunction() {
  return "Unused in app";
}

main();

export {
  main,
  unusedAppFunction,
}
/*  Not a pure module */
